### PR TITLE
Jobid feature

### PR DESCRIPTION
**Pull request by grabear**
#54 
This PR adds the slurm JobID to the slurm_job object, which is returned after submitting jobs.  This will be helpful for create slurm dependencies.

### CODE REVIEW

**Comment by qdread** [comment]
Thanks for the PR! I think there is an issue here that is causing the travis-ci check to fail. It looks like if you call `slurm_apply()` or similar with `submit = FALSE`, the `jobid` variable isn't defined within the function, so the function returns an error at the final line where it is trying to create the `slurm_job` object and return it. Since the vignette does this on line 63, the call to `slurm_apply()` returns an error and the vignette does not build.

**Comment by qdread** [comment]
Hi again @grabear , I will take over working on this to resolve the error. I am a little nervous it will break backward compatibility as implemented, so I will need to check and make sure before merging the final PR.

**Comment by qdread** [comment]
@grabear if you don't mind, please give me write access to your forked repo so that I can push a commit on top of your PR commits. thanks!

**Comment by grabear** [comment]
@qdread Hey sorry for the late response.  I just started going back to work again.  I'll give you permissions on my branch.

**Comment by grabear** [comment]
You're good to go.  Seem's like a pretty easy fix.  Let me know if you need some assistance!

**Comment by qdread** [comment]
Sorry for the many commits. The fix itself was easy, but I think the behavior of `system()`, which we use in the package tests, changed between R 3.6 and R 4.0. So the continuous integration tests are failing. I am working on resolving the issue.

**Comment by grabear** [comment]
@qdread Cheers! 🍻  Glad you got it working.  Sorry for not responding sooner.  I have a work account now, so I often get to check my personal account.

**Pull request merged**
