### PR TITLE
Support mc.cores greater than number of physical cores

### LINKED ISSUE #56: Support mc.cores greater than number of physical cores
Hi all. Thanks for your continued hard work on rslurm!

I'd like the ability to specify a larger number of cores in `parallel::mcmapply(mc.cores = N)` than is used for the job submission script's `--cpus-per-task=M`. Some SLURM clusters allocate resources based on the physical core count and will raise an error if `M` exceeds the number of physical cores on available nodes.

It would be great to have the option to use different values for `M` and `N` so the number of forked processes can be managed independently from SLURM allocation instructions. This could be accomplished by adding a `threads_per_core` argument (following [sbatch flags](https://slurm.schedmd.com/mc_support.html)) to `slurm_apply` and `slurm_map` where `N = as.integer(threads_per_core * M)`. Or `M` and `N` could be specified independently with the default retaining the current behavior.

Let me know your thoughts. I'm happy to implement and submit a PR if it would be helpful.

### PR DESCRIPTION
**Pull request by benfasoli**
This adds a `processes_per_node` argument which is passed to `parallel::mcmapply(mc.cores = processes_per_node)`. Specifying `processes_per_node > cpus_per_node` can more efficiently utilize nodes supporting hyperthreading.

The default behavior is `processes_per_node = cpus_per_node` for backwards compatibility.

Closes #56

### CODE REVIEW

**Comment by qdread** [comment]
Thanks @benfasoli ! I will take a look shortly.

**Comment by qdread** [comment]
Hey @benfasoli I'm testing out the PR but I think there is a bug still: check out for example line 173 in slurm_apply.R. There you need to pass the `processes_per_node` argument to `whisker.render()`. Otherwise, the `slurm_run_R.txt` template generates a `slurm_run.R` file with an empty argument for `mc.cores`. That would need to be fixed in a few places, I think. Do you mind going through and fixing that in the relevant places? thanks!

**Comment by benfasoli** [comment]
Nice catch. `processes_per_node` was being passed to the SLURM submission script template (where it is unused) and not to the R script template.

**Comment by qdread** [comment]
Wow that was quick! Thanks! 💯  ... I probably could have done it but I thought it would be fresher in your mind where all it was needed to fix.

**Comment by benfasoli** [comment]
Happy to help! Looks like this passes `devtools::test()` now.

**Pull request merged**
