### PR TITLE
Add library location specification

### PR DESCRIPTION
**Pull request by benfasoli**
Adds the ability to set lib.loc through the call to `library()` for specifying package locations.

### CODE REVIEW

**Comment by itcarroll** [comment]
Thanks for the contribution. Please run the package tests (`devtools::test()`) and try to resolve the errors or let us know where you get stuck.

**Comment by benfasoli** [comment]
I've resolved the testthat errors.

**Comment by itcarroll** [comment]
Thanks for your patience.

I've modified your proposal so that a user may specify additional paths to be added to the search path on a cluster node, rather than directly handing a lib.loc path to the library function. I think this is probably what you wanted to achieve. By passing a single path to lib.loc for *every* library call, you would be telling it to ignore the result of .libPaths() with whatever other custom paths it provides.

Let me know if this fulfills your needs, and I'll merge if checks pass.

**Comment by benfasoli** [comment]
Great, thanks!

**Pull request merged**
